### ISSUE TITLE
O nome da variável está correto?

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/opac_5#213]
### Descrição da tarefa

Consulte 
https://github.com/search?q=repo%3Ascieloorg%2Fopac_5%20OPAC_OPAC&type=code

<img width="753" alt="Captura de Tela 2024-11-19 às 17 27 24" src="https://github.com/user-attachments/assets/c7328b5e-3795-4d50-9160-0a32f91812a2">

`OPAC_` está duplicado sem querer?

**Comment by gitnnolabs** [comment]
@robertatakenaka 

Olhando aqui **está correto** o primeiro "OPAC" é o prefixo que adotamos no projeto para as variáveis de ambiente não se confundirem com outras variáveis do sistema operacional o seguindo "OPAC" se refere a aplicação que se chama OPAC. 

Essas variáveis de ambiente são utilizadas no envio de e-mail de auditoria, e para a geração de **COOKIE** da aplicação.
